version: '3.8'

services:
  timetrove-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: timetrove-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/${{ secrets.MYSQL_DATABASE }}?useSSL=false&allowPublicKeyRetrieval=true
      MYSQL_USERNAME: ${{ secrets.MYSQL_USERNAME }}
      MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      REDIS_HOST: redis
      REDIS_PORT: 6379
      KAKAO_CLIENT_ID: ${{ secrets.KAKAO_CLIENT_ID }}
      KAKAO_CLIENT_SECRET: ${{ secrets.KAKAO_CLIENT_SECRET }}
      EC2_DOMAIN: ${{ secrets.EC2_DOMAIN }}
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis
    networks:
      - timetrove-network
    restart: always

  timetrove-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: timetrove-frontend
    ports:
      - "3000:3000"
    networks:
      - timetrove-network
    depends_on:
      - timetrove-backend
    restart: always

  nginx:
    image: nginx:latest
    networks:
      - timetrove-network
    restart: always
    volumes:
      - ./conf/:/etc/nginx/conf.d
    ports:
      - "80:80"
    depends_on:
      - timetrove-backend
      - timetrove-frontend

  redis:
    image: redis:7.0
    ports:
      - "6379:6379"
    networks:
      - timetrove-network
    restart: always

networks:
  timetrove-network:
    driver: bridge
