#port
server:
   port: 80
#database application-datasource.xml
spring:
   datasource:
      url: jdbc:mysql://localhost:3306/mydb?autoReconnection=true
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
   jpa:
      database: mysql
      properties:
         hibernate:
           dialect: org.hibernate.dialect.MySQLDialect
           storage_engin: innodb
           show_sql: true
           format_sql: true
           user_sql_comments: true
   security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: d008d7a526a3e250c2bd63146f16c578
            client-secret: PyZvv74qu9JZNVHO2chFnpB9uBrqJpj0
            scope: 
              - profile_nickname
              - profile_image
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:3000/login/oauth2/callback/kakao
            client-authentication-method: client_secret_post
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
   web:
    resources:
      static-locations: file:./uploads/         

logging:
  level:
    org.springframework.security: DEBUG

