server:
  port: ${SERVER_PORT:80}

spring:
  jpa:
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        storage_engine: innodb
        show_sql: true
        format_sql: true
        user_sql_comments: true
        ddl-auto: validate
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

imp:
  api:
    key: ${IMP_API_KEY}
    secretkey: ${IMP_API_SECRET}

logging:
  level:
    org.springframework.security: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: INFO