server:
  port: 8080

spring:
  jpa:
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        storage_engine: innodb
        show_sql: true
        format_sql: true
        user_sql_comments: true
        ddl-auto: validate
  mvc:
    servlet:
      path: /api
  profiles:
    active: prod

logging:
  level:
    org.springframework.security: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: INFO